# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Specify the box to use
  config.vm.box = "generic/centos8"

  # Set a private network with a different IP if the current one is problematic
  config.vm.network "private_network", ip: "192.168.56.11" 

  # Public network (you may specify the adapter if necessary)
  config.vm.network "public_network", bridge: "en0: Wi-Fi (Wireless)"

  # VirtualBox specific settings
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
end
